### PR TITLE
#30 Add course selection layout 

### PR DESCRIPTION
**Pull request by KarineZhang**
- User can add and remove courses
- User can then submit the desired courses to find a study buddy match

### CODE REVIEW

**Comment by n2chao** [comment]
The layout is complete. The components to add and remove courses are there.

**Review by n2chao — APPROVED** [review]
The layout is complete. The components to add and remove courses are there.

**Comment by KarineZhang** [comment]
#80

**Comment by KarineZhang** [comment]
#80 #188

**Comment by KarineZhang** [comment]
#188

**Pull request merged**
