### PR TITLE
Student match

### PR DESCRIPTION
**Pull request by patrickspensieri**
Students can now book a meeting with each other. Unlike instructor meetings, student meetings require a `meeting request` be created and accepted before the actual `meeting` is booked. The `invited` user can accept/decline the request, while the `sender` can only decline the meeting request.

Once a meeting request is accepted, the actual meeting is created. If declined by either user, the request is closed.

For testing

- The `title` for users must be set to `student` manually in the database

- At least one other student must be enrolled for the given course

- At least one matching time slot between availabilities of both students

Also, the UI is just used to test, and should be edited to match the template UI.

### CODE REVIEW

**Comment by patrickspensieri** [comment]
WHY the `composer update`?

As of Laravel 5, the `Form` used in views is not included by default. Hence, the required dependencies for `Form` are added. 

- Added the package to `require` section of `composer.json`.

- Added providers to the `providers` section of `config/app.php`

- Added the aliases to the `aliases` section of `config/app.php`

- ran `composer update` from terminal

http://stackoverflow.com/questions/28753767/laravel-5-class-form-not-found

**Comment by patrickspensieri** [comment]
I fixed the issue with the matching times, there was an error in the RequestController.

Bug fix : `user->schedule` changed to `user->schedule->freetime` in `RequestController.php`

**Comment by prich28** [comment]
@patrickspensieri 
I pulled the branch and I am trying to get two students to match. But after I select the course, the next page loaded is an error:

screen shot 2017-03-22 at 4 37 35 pm

**Comment by patrickspensieri** [comment]
New commits address two issues

- students without matches are now properly removed from students collection, fixing bug found by @prich28 . `$students->forget($student->id);` changed to `$students = $students->except($student->id);`

- form validation added to `choosecourse` and `choosestudent` views

[
image
](url)

**Comment by prich28** [comment]
@patrickspensieri 
This is great! Awesome!
There are some conflicts, I'll let you fix them as I don't want to mess around with any code I'm unfamiliar with.

**Comment by patrickspensieri** [comment]
Addresses issues 

- #9 / #34 
- #81 
- #87 
- #88 
- #89

**Pull request merged**
